import { getServerSession } from "next-auth";
import "./globals.css";

// Components
import { ParentLayout } from "@/components";
import { authOptions } from "@/lib/auth";

export const metadata = {
  title: "thrdr.",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return <ParentLayout session={session}>{children}</ParentLayout>;
}
