import React from "react";

import { ChildLayout } from "@/components";

import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";

export const metadata = {
  title: "thrdr.",
  description: "Generated by create next app",
};

const ProfileLayout = async ({ children }: { children: React.ReactNode }) => {
  const session = await getServerSession(authOptions);
  return <ChildLayout session={session}>{children}</ChildLayout>;
};

export default ProfileLayout;
