"use client";

// Chakra UI
import { ChakraProvider } from "@chakra-ui/react";
import { CacheProvider } from "@chakra-ui/next-js";
import { Container, Navbar } from "@/components";

// Next Auth
import { SessionProvider } from "next-auth/react";

// Google Fonts
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "thrdr. Sign Up",
  description: "Generated by create next app",
};

export default function SignUpLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
