import React from "react";

export const metadata = {
  title: "thrdr.",
  description: "Generated by create next app",
};

const ThreadLayout = async ({ children }: { children: React.ReactNode }) => {
  return <>{children}</>;
};

export default ThreadLayout;
